### PR TITLE
updated instructor page

### PR DESCRIPTION
**Pull request by hasanahmed1810**
image

### CODE REVIEW

**Comment by yoshinodev** [comment]
Good. Note: When every crucial pages are changed, let's add a brief text above/under the instructors as they will be replaced by ai bots in future probably. @hasanahmed1810

**Review by yoshinodev — COMMENTED** [review]
Good, simple and direct to the point

**Comment by hasanahmed1810** [comment]
right ill add the extra texts for them in the remaining pages

**Comment by hasanahmed1810** [comment]
ill continue tomorrow

**Pull request merged**
